import os

ELEVEN_API_KEY         = os.getenv("ELEVEN_API_KEY")
ELEVEN_VOICE_ID        = os.getenv("ELEVEN_VOICE_ID")
AZURE_OPENAI_API_KEY   = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_ENDPOINT  = os.getenv("AZURE_OPENAI_ENDPOINT")
SYSTEM_PROMPT          = os.getenv("SYSTEM_PROMPT")

SAMPLE_RATE = 16000
CHANNELS = 1
SILENCE_THRESHOLD = 0.01
SILENCE_DURATION = 0.75
KB_FILE = 'kb.txt'
